### PR TITLE
#167891577 Login with Google and Facebook

### PR DESCRIPTION
**Pull request by tvpeter**
#### What does this PR do?

- Adds login with google and facebook into the app

#### Description of Task to be completed?

- create google and facebook project

- obtain app details

- setup endpoints to read user profile and search for user in the db

- redirect user to dashboard or return error

#### How should this be manually tested?

- clone the repo and run `npm install` to install all the packages

- add your email address and facebook emails to the users seeders file found in the database subdirectory

- run `npm run migrate && npm run seed` to create and insert user sample data

- change your `.env` config, set your app port to `3000` to tally with facebook and google whitelist uri's

- run 'npm run devstart` to start the app in development mode

- visit `api/v1/auth/google` and `/api/v1/auth/facebook` to login with google and facebook

#### Any background context you want to provide?

- none
#### What are the relevant pivotal tracker stories?

[#167891577](https://www.pivotaltracker.com/story/show/167891577)

#### Questions:

### CODE REVIEW

**Review by Pomile — COMMENTED** [review]
Well done!

I noticed that in the passport strategy callback, you did not check if the user profile provided by facebook includes email(s). Some users might not register with their email address on facebook.
Please consider a condition that checks if a user email address is available in the profile.

Also in the Travis test result. I noticed an error message as described below.

`== 20190817131405-create-users: migrating =======
Unhandled rejection SequelizeDatabaseError: relation "Companies" does not exist`

**Comment by tvpeter** [comment]
> Well done!
> 
> I noticed that in the passport strategy callback, you did not check if the user profile provided by facebook include email(s). some users might not register on facebook with their email address.
> 
> Also in the travis test result. I noticed an error message as described below.
> 
> `== 20190817131405-create-users: migrating ======= Unhandled rejection SequelizeDatabaseError: relation "Companies" does not exist`

I checked for Facebook also. here's the line `const userDetails = profile.emails[0].value ? profile.emails[0].value : profile.displayName; `

Yeah, I got that error after rebasing, trying to fix it.
Thanks

**Comment by Pomile** [comment]
> > Well done!
> > I noticed that in the passport strategy callback, you did not check if the user profile provided by facebook include email(s). some users might not register on facebook with their email address.
> > Also in the travis test result. I noticed an error message as described below.
> > `== 20190817131405-create-users: migrating ======= Unhandled rejection SequelizeDatabaseError: relation "Companies" does not exist`
> 
> I checked for Facebook also. here's the line `const userDetails = profile.emails[0].value ? profile.emails[0].value : profile.displayName; `
> 
> Yeah, I got that error after rebasing, trying to fix it.
> Thanks

Well done!

**Comment by tvpeter** [comment]
> > > Well done!
> > > I noticed that in the passport strategy callback, you did not check if the user profile provided by facebook include email(s). some users might not register on facebook with their email address.
> > > Also in the travis test result. I noticed an error message as described below.
> > > `== 20190817131405-create-users: migrating ======= Unhandled rejection SequelizeDatabaseError: relation "Companies" does not exist`
> > 
> > 
> > I checked for Facebook also. here's the line `const userDetails = profile.emails[0].value ? profile.emails[0].value : profile.displayName; `
> > Yeah, I got that error after rebasing, trying to fix it.
> > Thanks
> 
> Well done!

Fixed the error.
Thanks.

**Pull request merged**
